# -*- coding: utf-8 -*-
"""titanicreal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13uFoQIrFc-graJwPvE40QdNo7BxGg2E4

# CLEANING THE **FILE**
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np

df = pd.read_csv('Titanic.csv')

df.head(10)

df.tail()

df.shape

df.info()

df.drop("deck", axis=1, inplace=True)

df.drop("Unnamed: 0", axis=1, inplace=True)

df["age"] = df["age"].fillna(df["age"].mean())

df.info()

df["embark_town"] = df["embark_town"].fillna(df["embark_town"].mode()[0])

df.info()

df["embarked"] = df["embarked"].fillna(df["embarked"].mode()[0])

df.info()

df["embarked"].isnull().sum()

df.duplicated().sum()

df=df.drop_duplicates()

df.shape

df["sex"]

df["sex"]=df["sex"].map({"male":1,"female":0})

df["sex"]

df["adult_male"]=df["adult_male"].map({True:1,False:0})

df["alone"]

df["alone"]=df["alone"].map({True:1,False:0})

df['alone']

df.info()

df=pd.get_dummies(df,columns=["embarked"],drop_first=True)

df.head()

df["who"].value_counts()

df['embark_town']

df=pd.get_dummies(df,columns=["embark_town"],drop_first=True)

df.info()

df=pd.get_dummies(df,columns=["who"],drop_first=True)

df.info()

df['alive']

df["alone"]=df["alone"].map({'yes':1,'no':0})

df.info()

df['alive']

df["alive"]=df["alive"].map({'yes':1,'no':0})

df.info()

df['class'].value_counts()

df['class']=df['class'].map({'First':3,'Second':2,'Third':1})

df.info()

df["alone"].isnull().sum()

df.drop(columns=["alone"], inplace=True)

df.info()

df=df.replace({True:1,False:0})

df.info()

df.to_csv("cleaned_titanic_yes.csv",index=False)

files.download("cleaned_titanic_yes.csv")

